branch-defaults:
  dev:
    environment: null
    group_suffix: null
global:
  application_name: media_queue
  default_ec2_keyname: media_queue
  default_platform: python3.4
  default_region: us-west-2
  profile: eb-cli
  sc: git
